//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGrade
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Year { get; set; }
        public string CourseName { get; set; }
        public Nullable<double> HomeworkAvg { get; set; }
    }
}
